### PR TITLE
Fix more illusion stats

### LINKED ISSUE #276: Fix illusions to use diminishing stat return
Currently any time you summon an illusion passed level 25, the illusion is stronger than you. This is because dota calculates the stats for that level when they spawn them, so our level up code doesn't edit the stats. We need to hook on them being summoned and adjust their stats to match the hero they were created from.

### LINKED ISSUE #663: Morphling's Hybrid Illusion stats
Hybrid uses Morphling's stats not the targets

### PR DESCRIPTION
**Pull request by Trildar**
Fixes stats for Hybrid and Tempest Double. Closes #663. Hopefully closes #276.

### CODE REVIEW

File: game/scripts/vscripts/components/progression/hero_progression.lua [hunk 1]
```diff
@@ -5,96 +5,114 @@ if HeroProgression == nil then
     ChatCommand:LinkCommand("-levelup", "OnLevelUpChatCmd", HeroProgression)
 end
 
+GameEvents:OnPlayerLevelUp(function(keys)
```
Comment (chrisinajar) [inline game/scripts/vscripts/components/progression/hero_progression.lua]: Why remove this from init?

Comment (Trildar) [inline game/scripts/vscripts/components/progression/hero_progression.lua]: For some reason the event listeners seem to reset when `script_reload` is called. So having these in init made this component pretty much stop working whenever `script_reload` was done.

Comment (chrisinajar) [inline game/scripts/vscripts/components/progression/hero_progression.lua]: What's `script_reload`?

Comment (Trildar) [inline game/scripts/vscripts/components/progression/hero_progression.lua]: A console command. Reloads Lua scripts so that at least some things can be changed and tested without having to restart the whole map.

**Comment by Trildar** [comment]
Probably hold on this anyway. I just realised Rubick could potentially derp the system. Will work on that tomorrow.

**Comment by Haganeko** [comment]
Couldn't a morphling with manta also derp the system? As in, the illusions would have pre morph stats

**Comment by Trildar** [comment]
Nah, I covered that case already. Morphling illusions copy strength and agility from the original by just vanilla code, so I just made it only adjust intelligence for any Morphling illusion. Rubick is a potential issue due to incomplete coverage for Tempest Double. I thought it would be fine because there's only an issue if Tempest Double is first cast when over level 25.

**Comment by Haganeko** [comment]
What about a morphed Rubick?

**Comment by Trildar** [comment]
Morphed Rubick doesn't copy stats for illusions in vanilla. The current system should work fine and apply unmorphed stats.

**Comment by Trildar** [comment]
Should be fine to merge now. Assuming the event registry thing is fine. I can move it back if you really want since it should be fine in actual games.
